# Generated by Django 3.2.5 on 2022-07-29 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_remove_orders_mobile'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=255)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default=None, max_length=255)),
                ('plan', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.plans')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='alternative_mobile_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.DeleteModel(
            name='UserMobileNo',
        ),
    ]
