# Generated by Django 3.2.5 on 2022-07-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220729_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='plan',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plans'),
        ),
    ]
