# Generated by Django 3.2.5 on 2022-07-30 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220729_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plans',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
