# Generated by Django 3.2.5 on 2022-07-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220730_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='plan',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plans'),
        ),
    ]
