# Generated by Django 3.2.5 on 2022-07-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userdetails_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_durations',
            field=models.CharField(choices=[(1, '1 Months'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (7, '7 Months'), (8, '8 Months'), (9, '9 Months'), (10, '10 Months'), (11, '11 Months'), (12, '12 Months')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
