# Generated by Django 3.2.5 on 2022-07-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_plans_plan_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='plan_activated_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='userdetails',
            name='plan_expires_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
