# Generated by Django 3.2.5 on 2022-07-30 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_auto_20220730_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='plan_durations',
            new_name='durations',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='plan_activated_date',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='plan_expires_date',
        ),
        migrations.CreateModel(
            name='UserPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('activated_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('expire_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('plan', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.plans')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
