# Generated by Django 3.2.5 on 2022-07-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220730_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplans',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
