# Generated by Django 3.2.5 on 2022-09-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userplans_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.TextField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='plans',
            name='durations',
            field=models.CharField(choices=[('1', '1 Months'), ('2', '2 Months'), ('3', '3 Months'), ('4', '4 Months'), ('5', '5 Months'), ('6', '6 Months'), ('7', '7 Months'), ('8', '8 Months'), ('9', '9 Months'), ('10', '10 Months'), ('11', '11 Months'), ('12', '12 Months')], max_length=50),
        ),
    ]
