# Generated by Django 3.2.5 on 2022-09-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20220912_0814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
    ]
