# Generated by Django 3.2.5 on 2021-07-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_search'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Search',
        ),
    ]
