# Generated by Django 3.2.5 on 2022-07-28 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210727_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='quantity',
            new_name='total_amount',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='product_id',
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orders')),
            ],
        ),
    ]
