# Generated by Django 3.2.5 on 2022-07-29 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20220728_0601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name_plural': 'User Cart'},
        ),
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'User Order Items'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'User Orders'},
        ),
        migrations.AlterModelOptions(
            name='prodbrand',
            options={'verbose_name_plural': 'Brands'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name_plural': 'Products'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'verbose_name_plural': 'Sub Category'},
        ),
    ]
