# Generated by Django 3.2.5 on 2022-07-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20220729_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='mobile',
        ),
    ]
