# Generated by Django 3.2.5 on 2022-09-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_orderitems_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
